### ISSUE TITLE
【Android】com.google.android.recaptcha.internal.zzaj.invokeSuspend

### ISSUE THREAD

**Issue by wei9202** [GoogleCloudPlatform/recaptcha-enterprise-mobile-sdk#114]
main (native):tid=1 systid=21799 
#00 pc 0x5e488 libc.so (syscall + 28)
#01 pc 0x130fb3 libart.so (art::ConditionVariable::WaitHoldingLocks(art::Thread*) + 82)
#02 pc 0x4cd26b libart.so (art::GoToRunnable(art::Thread*) + 338)
#03 pc 0x4cd0f1 libart.so (art::JniMethodEnd(unsigned int, art::Thread*) + 8)
       at android.content.res.AssetManager.nativeSetConfiguration(Native method)
       at android.content.res.AssetManager.setConfiguration(AssetManager.java:1449)
       at android.content.res.ResourcesImpl.updateConfiguration(ResourcesImpl.java:482)
       at android.content.res.MiuiResourcesImpl.updateConfiguration(MiuiResourcesImpl.java:237)
       at android.content.res.ResourcesImpl.<init>(ResourcesImpl.java:207)
       at android.content.res.MiuiResourcesImpl.<init>(MiuiResourcesImpl.java:71)
       at android.app.ResourcesManager.originalCreateResourcesImpl(ResourcesManager.java:569)
       at android.app.ResourcesManager.createResourcesImpl(ResourcesManager.java:551)
       at android.app.ResourcesManager.findOrCreateResourcesImplForKeyLocked(ResourcesManager.java:601)
       at android.app.ResourcesManager.createResources(ResourcesManager.java:860)
       at android.app.ResourcesManager.getResources(ResourcesManager.java:929)
       at android.app.ContextImpl.createResources(ContextImpl.java:2269)
       at android.app.ContextImpl.createApplicationContext(ContextImpl.java:2292)
       at android.content.ContextWrapper.createApplicationContext(ContextWrapper.java:959)
       at android.webkit.WebViewFactory.getWebViewContextAndSetProvider(WebViewFactory.java:380)
       at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:402)
       at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:252)
       at android.webkit.WebView.getFactory(WebView.java:2582)
       at android.webkit.WebView.ensureProviderCreated(WebView.java:2576)
       at android.webkit.WebView.setOverScrollMode(WebView.java:2644)
       at android.view.View.<init>(View.java:5577)
       at android.view.View.<init>(View.java:5727)
       at android.view.ViewGroup.<init>(ViewGroup.java:700)
       at android.widget.AbsoluteLayout.<init>(AbsoluteLayout.java:56)
       at android.webkit.WebView.<init>(WebView.java:413)
       at android.webkit.WebView.<init>(WebView.java:355)
       at android.webkit.WebView.<init>(WebView.java:337)
       at android.webkit.WebView.<init>(WebView.java:324)
       at android.webkit.WebView.<init>(WebView.java:314)
       at com.google.android.recaptcha.internal.zzaj.invokeSuspend(com.google.android.recaptcha:recaptcha@@18.4.0:4)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:236)
       at android.app.ActivityThread.main(ActivityThread.java:8097)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)

**Comment by wei9202** [comment]
I want to see the update history of recaptcha. Where can I see what has been updated from 18.4.2 to 18.5.1?

**Comment by mcorner** [comment]
Would you mind refiling this using the issue template?

**Comment by wei9202** [comment]
![image](https://github.com/GoogleCloudPlatform/recaptcha-enterprise-mobile-sdk/assets/172582376/a53f5160-e7d5-4c21-9690-001e1a964e1f)
![image](https://github.com/GoogleCloudPlatform/recaptcha-enterprise-mobile-sdk/assets/172582376/e9b38ac5-175a-425e-812a-4186d6fa2c97)
          main (runnable):tid=1 systid=3609 
#00 pc 0x535c24 libart.so (art::DumpNativeStack(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, int, BacktraceMap*, char const*, art::ArtMethod*, void*, bool) + 128) (BuildId: 28c5aa8a2e8fc5df069f717d6e94f7fe)
#01 pc 0x6efd94 libart.so (art::Thread::DumpStack(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, bool, BacktraceMap*, bool) const + 236) (BuildId: 28c5aa8a2e8fc5df069f717d6e94f7fe)
#02 pc 0x6fd620 libart.so (art::DumpCheckpoint::Run(art::Thread*) + 208) (BuildId: 28c5aa8a2e8fc5df069f717d6e94f7fe)
#03 pc 0x400a74 libart.so (art::Thread::RunCheckpointFunction() + 140) (BuildId: 28c5aa8a2e8fc5df069f717d6e94f7fe)
#04 pc 0x396544 libart.so (art::ClassLinker::LoadClass(art::Thread*, art::DexFile const&, art::dex::ClassDef const&, art::Handle<art::mirror::Class>) + 4744) (BuildId: 28c5aa8a2e8fc5df069f717d6e94f7fe)
#05 pc 0x38f960 libart.so (art::ClassLinker::DefineClass(art::Thread*, char const*, unsigned long, art::Handle<art::mirror::ClassLoader>, art::DexFile const&, art::dex::ClassDef const&) + 1688) (BuildId: 28c5aa8a2e8fc5df069f717d6e94f7fe)
#06 pc 0x38d00c libart.so (art::ClassLinker::FindClassInBaseDexClassLoader(art::ScopedObjectAccessAlreadyRunnable&, art::Thread*, char const*, unsigned long, art::Handle<art::mirror::ClassLoader>, art::ObjPtr<art::mirror::Class>*) + 1036) (BuildId: 28c5aa8a2e8fc5df069f717d6e94f7fe)
#07 pc 0x388f78 libart.so (art::ClassLinker::FindClass(art::Thread*, char const*, art::Handle<art::mirror::ClassLoader>) + 1032) (BuildId: 28c5aa8a2e8fc5df069f717d6e94f7fe)
#08 pc 0x5fee50 libart.so (art::Class_classForName(_JNIEnv*, _jclass*, _jstring*, unsigned char, _jobject*) (.__uniq.181829539739573773940154555818377431209) + 276) (BuildId: 28c5aa8a2e8fc5df069f717d6e94f7fe)
       at java.lang.Class.classForName(Native method)
       at java.lang.Class.forName(Class.java:454)
       at android.webkit.WebViewFactory.getWebViewProviderClass(WebViewFactory.java:271)
       at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:519)
       at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:348)
       at android.webkit.WebView.getFactory(WebView.java:2594)
       at android.webkit.WebView.ensureProviderCreated(WebView.java:2588)
       at android.webkit.WebView.setOverScrollMode(WebView.java:2656)
       at android.view.View.<init>(View.java:5411)
       at android.view.View.<init>(View.java:5570)
       at android.view.ViewGroup.<init>(ViewGroup.java:715)
       at android.widget.AbsoluteLayout.<init>(AbsoluteLayout.java:56)
       at android.webkit.WebView.<init>(WebView.java:421)
       at android.webkit.WebView.<init>(WebView.java:363)
       at android.webkit.WebView.<init>(WebView.java:345)
       at android.webkit.WebView.<init>(WebView.java:332)
       at android.webkit.WebView.<init>(WebView.java:322)
       at com.google.android.recaptcha.internal.zzaj.invokeSuspend(com.google.android.recaptcha:recaptcha@@18.4.0:4)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
       at android.os.Handler.handleCallback(Handler.java:942)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:211)
       at android.os.Looper.loop(Looper.java:300)
       at android.app.ActivityThread.main(ActivityThread.java:8315)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:581)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)

**Comment by mcorner** [comment]
Unfortunately we will close this due to a lack of response
