### ISSUE TITLE
ANR issues on Android

### ISSUE THREAD

**Issue by mnayef95-tlb** [GoogleCloudPlatform/recaptcha-enterprise-mobile-sdk#127]
**Describe the bug**
Hello, we recently transitioned to Flutter and are now using the reCAPTCHA Flutter SDK version 18.2.2+1. Since the update, we've noticed some ANRs reported on Google Play related to reCAPTCHA.

Is updating the SDK going to help here?

Stacktrace:
```
com.google.android.recaptcha.internal.zzv.zza
          main (runnable):tid=1 systid=25212 
#00 pc 0x4a07d0 libart.so (art::DumpNativeStack(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, int, BacktraceMap*, char const*, art::ArtMethod*, void*, bool) + 140)
#01 pc 0x5ada14 libart.so (art::Thread::DumpStack(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, bool, BacktraceMap*, bool) const + 376)
#02 pc 0x5cab4c libart.so (art::DumpCheckpoint::Run(art::Thread*) + 924)
#03 pc 0x5ae948 libart.so (art::Thread::RunCheckpointFunction() + 176)
#04 pc 0x1d4908 libart.so (art::ClassLinker::LoadClass(art::Thread*, art::DexFile const&, art::dex::ClassDef const&, art::Handle<art::mirror::Class>) + 1356)
#05 pc 0x1d1274 libart.so (art::ClassLinker::DefineClass(art::Thread*, char const*, unsigned long, art::Handle<art::mirror::ClassLoader>, art::DexFile const&, art::dex::ClassDef const&) + 940)
#06 pc 0x1f653c libart.so (void* art::VisitClassLoaderDexFiles<void art::VisitClassLoaderDexFiles<art::ClassLinker::FindClassInBaseDexClassLoaderClassPath(art::ScopedObjectAccessAlreadyRunnable&, char const*, unsigned long, art::Handle<art::mirror::ClassLoader>)::$_30>(art::ScopedObjectAccessAlreadyRunnable&, art::Handle<art::mirror::ClassLoader>, art::ClassLinker::FindClassInBaseDexClassLoaderClassPath(art::ScopedObjectAccessAlreadyRunnable&, char const*, unsigned long, art::Handle<art::mirror::ClassLoader>)::$_30)::'lambda'(art::DexFile const*, void**), void*>(art::ScopedObjectAccessAlreadyRunnable&, art::Handle<art::mirror::ClassLoader>, art::ClassLinker::FindClassInBaseDexClassLoaderClassPath(art::ScopedObjectAccessAlreadyRunnable&, char const*, unsigned long, art::Handle<art::mirror::ClassLoader>)::$_30, void*) + 752)
#07 pc 0x1d0568 libart.so (art::ClassLinker::FindClassInBaseDexClassLoader(art::ScopedObjectAccessAlreadyRunnable&, art::Thread*, char const*, unsigned long, art::Handle<art::mirror::ClassLoader>, art::ObjPtr<art::mirror::Class>*) + 644)
#08 pc 0x1d1d38 libart.so (art::ClassLinker::FindClass(art::Thread*, char const*, art::Handle<art::mirror::ClassLoader>) + 1064)
#09 pc 0x1be258 libart.so (art::ClassLinker::DoResolveType(art::dex::TypeIndex, art::Handle<art::mirror::DexCache>, art::Handle<art::mirror::ClassLoader>) + 184)
#10 pc 0x1be81c libart.so (art::ObjPtr<art::mirror::Class> art::ClassLinker::DoResolveType<art::ObjPtr<art::mirror::Class> >(art::dex::TypeIndex, art::ObjPtr<art::mirror::Class>) + 240)
#11 pc 0x1d4b2c libart.so (art::ClassLinker::LoadSuperAndInterfaces(art::Handle<art::mirror::Class>, art::DexFile const&) + 240)
#12 pc 0x1d12c8 libart.so (art::ClassLinker::DefineClass(art::Thread*, char const*, unsigned long, art::Handle<art::mirror::ClassLoader>, art::DexFile const&, art::dex::ClassDef const&) + 1024)
#13 pc 0x1f653c libart.so (void* art::VisitClassLoaderDexFiles<void art::VisitClassLoaderDexFiles<art::ClassLinker::FindClassInBaseDexClassLoaderClassPath(art::ScopedObjectAccessAlreadyRunnable&, char const*, unsigned long, art::Handle<art::mirror::ClassLoader>)::$_30>(art::ScopedObjectAccessAlreadyRunnable&, art::Handle<art::mirror::ClassLoader>, art::ClassLinker::FindClassInBaseDexClassLoaderClassPath(art::ScopedObjectAccessAlreadyRunnable&, char const*, unsigned long, art::Handle<art::mirror::ClassLoader>)::$_30)::'lambda'(art::DexFile const*, void**), void*>(art::ScopedObjectAccessAlreadyRunnable&, art::Handle<art::mirror::ClassLoader>, art::ClassLinker::FindClassInBaseDexClassLoaderClassPath(art::ScopedObjectAccessAlreadyRunnable&, char const*, unsigned long, art::Handle<art::mirror::ClassLoader>)::$_30, void*) + 752)
#14 pc 0x1d0568 libart.so (art::ClassLinker::FindClassInBaseDexClassLoader(art::ScopedObjectAccessAlreadyRunnable&, art::Thread*, char const*, unsigned long, art::Handle<art::mirror::ClassLoader>, art::ObjPtr<art::mirror::Class>*) + 644)
#15 pc 0x1d1d38 libart.so (art::ClassLinker::FindClass(art::Thread*, char const*, art::Handle<art::mirror::ClassLoader>) + 1064)
#16 pc 0x4bad50 libart.so (art::Class_classForName(_JNIEnv*, _jclass*, _jstring*, unsigned char, _jobject*) + 240)
       at java.lang.Class.classForName(Native method)
       at java.lang.Class.forName(Class.java:454)
       at android.webkit.WebViewFactory.getWebViewProviderClass(WebViewFactory.java:176)
       at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:423)
       at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:252)
       at android.webkit.WebView.getFactory(WebView.java:2576)
       at android.webkit.WebView.ensureProviderCreated(WebView.java:2570)
       at android.webkit.WebView.setOverScrollMode(WebView.java:2638)
       at android.view.View.<init>(View.java:5338)
       at android.view.View.<init>(View.java:5484)
       at android.view.ViewGroup.<init>(ViewGroup.java:697)
       at android.widget.AbsoluteLayout.<init>(AbsoluteLayout.java:56)
       at android.webkit.WebView.<init>(WebView.java:413)
       at android.webkit.WebView.<init>(WebView.java:355)
       at android.webkit.WebView.<init>(WebView.java:337)
       at android.webkit.WebView.<init>(WebView.java:324)
       at android.webkit.WebView.<init>(WebView.java:314)
       at com.google.android.recaptcha.internal.zzv.zza(com.google.android.recaptcha:recaptcha@@18.2.1:13)
       at com.google.android.recaptcha.internal.zzv.zzb(com.google.android.recaptcha:recaptcha@@18.2.1:2)
       at com.google.android.recaptcha.Recaptcha$getClient$2$1.invokeSuspend(com.google.android.recaptcha:recaptcha@@18.2.1:3)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:250)
       at android.app.ActivityThread.main(ActivityThread.java:7851)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958
```

**Integration Method**
Flutter

**SDK Version:** 18.2.2+1

**To Reproduce**

We can't reproduce it locally

**Expected behavior**
The app should be responsive

**Comment by walterjgsp** [comment]
@mnayef95-tlb thanks for the review! This will happen in lower end devices and we are continuously working to improve the experience of those devices. 

One suggestion that I can give you is to update to the newest version of the SDK in Flutter. Could you try with 18.6.1 and see if the experience and the ANR ratios are better/solved there?

**Comment by walterjgsp** [comment]
I hope it improves! Please let me know if it does not work and we can investigate internally what's happening @mnayef95-tlb.

We also do have a new API there that provides better user experience and lower latencies on init with built-in retries. If possible when you migrate to 18.6.1 in Flutter please also try the `fetchClient` API.
