### ISSUE TITLE
Crash on iOS

### ISSUE THREAD

**Issue by SurglogsGithubUser** [GoogleCloudPlatform/recaptcha-enterprise-mobile-sdk#22]
**Crash on application build to TF. **

There is a weird crash in app, which is build to TestFlight after update of reCAPTCHA to version 18.0.3.
It will crash randlomly on random places. I have a lot of stacktraces and its all over the place. 

**Integration Method**

Select the method used to integrate with reCAPTCHA Mobile.

 

- [ ] SPM

**SDK Version (e.g. 18.0.1): 18.0.3 **

**Xcode version (please complete the following information)**
 - Version Xcode 14.2

**Device (please complete the following information):**
 - Model: iPhone12 mini, iPhone 13 Pro
 - OS: 16.1, 16.2
 - Only real device

**Additional context**

I can send you privatelly a lot of stackt traces

**Comment by mcorner** [comment]
Huh, could be some new XCode incompatibility.  To confirm:

- This is only testflight, not a regular release build?
- Have you tried an older Xcode version?
- This is only 18.0.3?  Does 18.0.2 similarly crash?

And yes, the stack traces may be helpful.   Mail to my firstnamelastname@google.com

We will try to replicate.

**Comment by mcorner** [comment]
I just ran a local build on XCode Version 14.2 (14C18) with 18.0.3 and it ran fine.  So more digging will be needed.

**Comment by SurglogsGithubUser** [comment]
I tried only TestFlight, i have no quick way to build release build directly to physical device. I can investigate more at the end of the month, now it does not have priority. 
But i Will send You stacktraces to email and if you have any question dont hesitate to ask. 
Thank You

**Comment by mcorner** [comment]
If you have any more information about this, let us know.  We haven't been able to reproduce it.

**Comment by mcorner** [comment]
Quick question: Do you still have the protobuf library included?  It is wrapped inside of 18.0.3 and 18.1.0 and I am wondering if there is something going on with that.  It really shouldn't...f

But how often does this happen?  Of course if you can reduce it to a small reproduction we would be able to track it down faster since we haven't seen this.

**Comment by SurglogsGithubUser** [comment]
You are right, there is no protobuf on this version. 
And its happening on every run of the app, usually in mather of minutes after startup.
I will try to reproduce it on small app

**Comment by jacobocl** [comment]
We have the same problem. Random crashes on iOS when using Recaptcha Enterprise. Sometimes it's a Heap Corruption, but other times it's a different crash.

**Comment by SurglogsGithubUser** [comment]
I was not able to simulate it on small app in the short time.

**Comment by mcorner** [comment]
We have run Address Sanitizer (https://developer.apple.com/documentation/xcode/diagnosing-memory-thread-and-crash-issues-early) which doesn't reveal any memory issues thus far.  Perhaps you can run it as well and let me know if you find anything.

**Comment by mcorner** [comment]
@SurglogsGithubUser We did fix a race condition in 18.1.0 involving the code from your stack traces.  Have you tried replicating it on that SDK version?

**Comment by jacobocl** [comment]
@mcorner I just run the Address Sanitizer and this is the message that I got in the console:
```

==1405==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x00012985de50 at pc 0x00010415e274 bp 0x00016d645bf0 sp 0x00016d645be8
WRITE of size 1 at 0x00012985de50 thread T60
2023-03-14 11:26:06.009902+0100 App[1405:47405] 9.1.0 - [FirebasePerformance][I-PRF100009] Logging network request trace - https://www.recaptcha.net/recaptcha/api3/mlg, Response code: 200, 205.8270ms
2023-03-14 11:26:06.010270+0100 App[1405:47405] 9.1.0 - [FirebaseInstallations][I-FIS002000] -[FIRInstallationsIDController createGetInstallationItemPromise], appName: __FIRAPP_DEFAULT
2023-03-14 11:26:06.010467+0100 App[1405:47405] 9.1.0 - [FirebaseInstallations][I-FIS002001] -[FIRInstallationsIDController installationWithValidAuthTokenForcingRefresh:0], appName: __FIRAPP_DEFAULT
    #0 0x10415e270 in closure #1 (Swift.UnsafeRawBufferPointer) -> Swift.Bool in static Foundation.Data.== infix(Foundation.Data, Foundation.Data) -> Swift.Bool+0x468 (/private/var/containers/Bundle/Application/BD485543-67BC-410C-B090-8DA83AD672A8/App.app/App:arm64+0x10191e270)
    #1 0x1041e86cc in generic specialization <Swift.Array<Foundation.Data>> of (extension in Swift):Swift.Sequence< where A.Element: Swift.Equatable>.contains(A.Element) -> Swift.Bool+0x260 (/private/var/containers/Bundle/Application/BD485543-67BC-410C-B090-8DA83AD672A8/App.app/App:arm64+0x1019a86cc)
    #2 0x1041e806c in googlemac_iPhone_recaptcha_enterprise_recaptcha_metrics_collection.lo0CeefR.(xxcRVuyD in _0CD010CDD72C13AFD3552EDBA5A1302F)(Swift.Array<Foundation.Data>) -> ()+0x4ec (/private/var/containers/Bundle/Application/BD485543-67BC-410C-B090-8DA83AD672A8/App.app/App:arm64+0x1019a806c)
    #3 0x1041e737c in googlemac_iPhone_recaptcha_enterprise_recaptcha_metrics_collection.lo0CeefR.g2TieryU(__C.RCAcbyikqoo) -> ()+0x214 (/private/var/containers/Bundle/Application/BD485543-67BC-410C-B090-8DA83AD672A8/App.app/App:arm64+0x1019a737c)
    #4 0x1041e6230 in function signature specialization <Arg[4] = Dead> of static googlemac_iPhone_recaptcha_enterprise_recaptcha_metrics_collection.rq7Pz2Cy.f0oBtbQ8(withEventId: googlemac_iPhone_recaptcha_enterprise_recaptcha_metrics_collection.EventID, status: __C.RCAcbyikqoo_sftiafgz, exception: Swift.Optional<__C.RCAException>, bTLr4K4A: Swift.Double) -> ()+0x150 (/private/var/containers/Bundle/Application/BD485543-67BC-410C-B090-8DA83AD672A8/App.app/App:arm64+0x1019a6230)
    #5 0x1041e6bd0 in partial apply forwarder for closure #1 () -> () in static googlemac_iPhone_recaptcha_enterprise_recaptcha_metrics_collection.rq7Pz2Cy.tjzIzWGb(googlemac_iPhone_recaptcha_enterprise_recaptcha_metrics_collection.EventID) -> ()+0x34 (/private/var/containers/Bundle/Application/BD485543-67BC-410C-B090-8DA83AD672A8/App.app/App:arm64+0x1019a6bd0)
    #6 0x1028b6eb4 in reabstraction thunk helper from @escaping @callee_guaranteed () -> () to @escaping @callee_unowned @convention(block) () -> ()+0x94 (/private/var/containers/Bundle/Application/BD485543-67BC-410C-B090-8DA83AD672A8/App.app/App:arm64+0x100076eb4)
    #7 0x106fff1c8 in __wrap_dispatch_async_block_invoke+0xc0 (/private/var/containers/Bundle/Application/BD485543-67BC-410C-B090-8DA83AD672A8/App.app/Frameworks/libclang_rt.asan_ios_dynamic.dylib:arm64e+0x3f1c8)
    #8 0x1096f4538 in _dispatch_call_block_and_release+0x1c (/usr/lib/system/introspection/libdispatch.dylib:arm64e+0x4538)
    #9 0x1096f5fec in _dispatch_client_callout+0x10 (/usr/lib/system/introspection/libdispatch.dylib:arm64e+0x5fec)
    #10 0x1096fe09c in _dispatch_lane_serial_drain+0x3d8 (/usr/lib/system/introspection/libdispatch.dylib:arm64e+0xe09c)
    #11 0x1096fedc4 in _dispatch_lane_invoke+0x1a0 (/usr/lib/system/introspection/libdispatch.dylib:arm64e+0xedc4)
    #12 0x10970bca8 in _dispatch_workloop_worker_thread+0x2e0 (/usr/lib/system/introspection/libdispatch.dylib:arm64e+0x1bca8)
    #13 0x20b820df4 in _pthread_wqthread+0x11c (/usr/lib/system/libsystem_pthread.dylib:arm64e+0xdf4)
    #14 0x20b820b94 in start_wqthread+0x4 (/usr/lib/system/libsystem_pthread.dylib:arm64e+0xb94)

0x00012985de50 is located 0 bytes to the right of 208-byte region [0x00012985dd80,0x00012985de50)
allocated by thread T60 here:
    #0 0x107000490 in wrap_calloc+0x9c (/private/var/containers/Bundle/Application/BD485543-67BC-410C-B090-8DA83AD672A8/App.app/Frameworks/libclang_rt.asan_ios_dynamic.dylib:arm64e+0x40490)
    #1 0x1b6722788 in class_createInstance+0x3c (/usr/lib/libobjc.A.dylib:arm64e+0x2788)
    #2 0x1b79a669c in NSAllocateObject+0x18 (/System/Library/Frameworks/Foundation.framework/Foundation:arm64e+0x9c69c)
    #3 0x1b795aeec in <redacted>+0x48 (/System/Library/Frameworks/Foundation.framework/Foundation:arm64e+0x50eec)
    #4 0x1b7d37294 in <redacted>+0x74 (/System/Library/Frameworks/Foundation.framework/Foundation:arm64e+0x42d294)
    #5 0x1041e71a0 in googlemac_iPhone_recaptcha_enterprise_recaptcha_metrics_collection.lo0CeefR.g2TieryU(__C.RCAcbyikqoo) -> ()+0x38 (/private/var/containers/Bundle/Application/BD485543-67BC-410C-B090-8DA83AD672A8/App.app/App:arm64+0x1019a71a0)
    #6 0x1041e6230 in function signature specialization <Arg[4] = Dead> of static googlemac_iPhone_recaptcha_enterprise_recaptcha_metrics_collection.rq7Pz2Cy.f0oBtbQ8(withEventId: googlemac_iPhone_recaptcha_enterprise_recaptcha_metrics_collection.EventID, status: __C.RCAcbyikqoo_sftiafgz, exception: Swift.Optional<__C.RCAException>, bTLr4K4A: Swift.Double) -> ()+0x150 (/private/var/containers/Bundle/Application/BD485543-67BC-410C-B090-8DA83AD672A8/App.app/App:arm64+0x1019a6230)
    #7 0x1041e6bd0 in partial apply forwarder for closure #1 () -> () in static googlemac_iPhone_recaptcha_enterprise_recaptcha_metrics_collection.rq7Pz2Cy.tjzIzWGb(googlemac_iPhone_recaptcha_enterprise_recaptcha_metrics_collection.EventID) -> ()+0x34 (/private/var/containers/Bundle/Application/BD485543-67BC-410C-B090-8DA83AD672A8/App.app/App:arm64+0x1019a6bd0)
    #8 0x1028b6eb4 in reabstraction thunk helper from @escaping @callee_guaranteed () -> () to @escaping @callee_unowned @convention(block) () -> ()+0x94 (/private/var/containers/Bundle/Application/BD485543-67BC-410C-B090-8DA83AD672A8/App.app/App:arm64+0x100076eb4)
    #9 0x106fff1c8 in __wrap_dispatch_async_block_invoke+0xc0 (/private/var/containers/Bundle/Application/BD485543-67BC-410C-B090-8DA83AD672A8/App.app/Frameworks/libclang_rt.asan_ios_dynamic.dylib:arm64e+0x3f1c8)
    #10 0x1096f4538 in _dispatch_call_block_and_release+0x1c (/usr/lib/system/introspection/libdispatch.dylib:arm64e+0x4538)
    #11 0x1096f5fec in _dispatch_client_callout+0x10 (/usr/lib/system/introspection/libdispatch.dylib:arm64e+0x5fec)
    #12 0x1096fe09c in _dispatch_lane_serial_drain+0x3d8 (/usr/lib/system/introspection/libdispatch.dylib:arm64e+0xe09c)
    #13 0x1096fedc4 in _dispatch_lane_invoke+0x1a0 (/usr/lib/system/introspection/libdispatch.dylib:arm64e+0xedc4)
    #14 0x10970bca8 in _dispatch_workloop_worker_thread+0x2e0 (/usr/lib/system/introspection/libdispatch.dylib:arm64e+0x1bca8)
    #15 0x20b820df4 in _pthread_wqthread+0x11c (/usr/lib/system/libsystem_pthread.dylib:arm64e+0xdf4)
    #16 0x20b820b94 in start_wqthread+0x4 (/usr/lib/system/libsystem_pthread.dylib:arm64e+0xb94)

Thread T60 created by T0 here:
    <empty stack>

SUMMARY: AddressSanitizer: heap-buffer-overflow (/private/var/containers/Bundle/Application/BD485543-67BC-410C-B090-8DA83AD672A8/App.app/App:arm64+0x10191e270) in closure #1 (Swift.UnsafeRawBufferPointer) -> Swift.Bool in static Foundation.Data.== infix(Foundation.Data, Foundation.Data) -> Swift.Bool+0x468
Shadow bytes around the buggy address:
  0x0002a532bb70: 00 00 00 00 00 00 00 00 00 00 00 00 fa fa fa fa
  0x0002a532bb80: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0002a532bb90: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0002a532bba0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0002a532bbb0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0002a532bbc0: 00 00 00 00 00 00 00 00 00 00[fa]fa fa fa fa fa
  0x0002a532bbd0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0002a532bbe0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0002a532bbf0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0002a532bc00: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0002a532bc10: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==1405==ABORTING
warning: hit breakpoint while running function, skipping commands and conditions to prevent recursion
AddressSanitizer report breakpoint hit. Use 'thread info -s' to get extended information about the report.
```

**Comment by mcorner** [comment]
Awesome!   A few questions: what exact sdk version are you using?   This is a release build?  Real device or simulator?  Is there any way you could strip this down to just the problem and share the project with us privately?

**Comment by jacobocl** [comment]
SDK Version: 18.1.0 (but I got the crash also on 18.0.3)

**Comment by mcorner** [comment]
duplicate #38

**Comment by mcorner** [comment]
Please leave further comments in #38
