### ISSUE TITLE
Getting too many INTERNAL_ERROR from executeTask

### ISSUE THREAD

**Issue by heetchKarakasli** [GoogleCloudPlatform/recaptcha-enterprise-mobile-sdk#25]
**Describe the bug**
We have been facing too many internal errors for our Android Client when call `executeTask`, about %30 of execution returns with INTERNAL_ERROR as we tracked on Firebase Crachlytics.

**Integration Method**
It is integrated via Gradle `com.google.android.recaptcha:recaptcha:18.0.0`

This is gradle configuration of our application. 
We are not sure, but this part is not same what documents says, Jetifier is not enabled for our app. 
So it is good to mention about this configuration for possible reasons.

```
android.useAndroidX=true
android.enableJetifier=false
```

**SDK Version (e.g. 18.0.1):** 
18.0.0

**To Reproduce**
Could not detect reproduce steps, we can get same issues time by time for staging or production for any Android Version or and android device brand. There is not any specific relation between android version or brand etc...

**Expected behavior**
We expect to see low ration who could not get token with any reason. We are trying to find reasons of Internal Error.

**Additional context**
Example stack trace;
```kotlin
com.heetch.recaptcha.GoogleRecaptchaProvider.observeToken$lambda$9$lambda$8 (GoogleRecaptchaProvider.kt:62)
com.heetch.recaptcha.GoogleRecaptchaProvider.$r8$lambda$dYJIsb4I-Hh2j4ttZbV0qbTKBuU
com.heetch.recaptcha.GoogleRecaptchaProvider$$ExternalSyntheticLambda0.onComplete (Unknown Source:2)
com.google.android.gms.tasks.zzi.run (com.google.android.gms:play-services-tasks@@18.0.2:1)
android.os.Handler.handleCallback (Handler.java:942)
android.os.Handler.dispatchMessage (Handler.java:99)
android.os.Looper.loopOnce (Looper.java:226)
android.os.Looper.loop (Looper.java:313)
android.app.ActivityThread.main (ActivityThread.java:8741)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:571)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1067)
```

GoogleRecaptchaProvider.kt:62 equals to row `emitter.onError(Throwable(task.exception))`

```kotlin
private fun RecaptchaTasksClient.observeToken(key: RecaptchaProvider.Action) = Single.create { emitter ->
        this.executeTask(getAction(key))
            .addOnCompleteListener { task ->
                if (task.isSuccessful) {
                    emitter.onSuccess(task.result)
                } else {
                    emitter.onError(Throwable(task.exception))
                }
            }
    }
```

**Comment by mcorner** [comment]
Please switch to 18.0.1, there were substantial improvements in execute failures (and there is more to come in the near future to best to keep an eye on the releases.

Thanks for the report.

**Comment by heetchKarakasli** [comment]
Hi @mcorner, 

We have updated SDK version to `18.0.1` and continue to track numbers for our users about 7 days. Before doing that we ignored to users who has potential internet connection issues by checking their authentication results after token exception.

End of the 7 days, our numbers are almost fixed to %9, it means %9 of users could not able to get token at least one time a day.

Here are some INTERNAL_ERROR logs from Crashlytics Reports;

**Most frequently**
```
Non-fatal Exception: com.google.android.recaptcha.RecaptchaException: Internal Error
       at com.google.android.recaptcha.internal.zzbf.zzb(com.google.android.recaptcha:recaptcha@@18.0.1:4)
       at com.google.android.recaptcha.internal.zzbf.onReceivedError(com.google.android.recaptcha:recaptcha@@18.0.1:2)
       at android.webkit.WebViewClient.onReceivedError(WebViewClient.java:337)
       at com.google.android.recaptcha.internal.zzbf.onReceivedError(com.google.android.recaptcha:recaptcha@@18.0.1:3)
       at YB0.c(YB0.java:61)
       at Ea.handleMessage(Ea.java:454)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:263)
       at android.app.ActivityThread.main(ActivityThread.java:8292)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1006)
```

**Second Most Frequently;**
```
Non-fatal Exception: java.lang.Throwable: kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 5000 ms
       at com.heetch.recaptcha.GoogleRecaptchaProvider.observeToken$lambda$9$lambda$8(GoogleRecaptchaProvider.java:62)
       at com.heetch.recaptcha.GoogleRecaptchaProvider$$InternalSyntheticLambda$5$416df1b00c435c8c730320d6531a4cf05cc44165751598f344685f82a2c342ec$0.onComplete(GoogleRecaptchaProvider.java:30)
       at com.google.android.gms.tasks.zzi.run(zzi.java:1)
       at com.google.android.gms.measurement.internal.zzhh.run$bridge(com.google.android.gms:play-services-measurement-impl@@20.1.0:94)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8669)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

**Third Most Frequently**
```
Non-fatal Exception: com.google.android.recaptcha.RecaptchaException: Internal Error.
       at com.google.android.recaptcha.internal.zzbh.zza(com.google.android.recaptcha:recaptcha@@18.0.1:8)
       at com.google.android.recaptcha.internal.zzbh.zzoid(com.google.android.recaptcha:recaptcha@@18.0.1:5)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:379)
       at android.os.Looper.loop(Looper.java:144)
       at android.os.HandlerThread.run(HandlerThread.java:65)
```

Thanks for your support.
