### ISSUE TITLE
Bug: Getting Recaptcha exception: Internal error, Network error when initializing recaptcha client in Android

### ISSUE THREAD

**Issue by rogu01** [GoogleCloudPlatform/recaptcha-enterprise-mobile-sdk#92]
**Describe the bug**

When initializing recaptcha client getting Recaptcha exception: Internal error, Network error in android

**reCAPTCHA Site Key**

will provide if required

**Integration Method**

Select the method used to integrate with reCAPTCHA Mobile.

GMaven (Android)

**SDK Version (e.g. 18.0.1):**

18.4.0

**To Reproduce**

We can't reproduce this issue during development or testing. I track this exception through crashlytics non-fatal. I have already implemented a retry mechanism. if the recaptcha client is not initialised in the application class due to any error. I am again initialising it in activity class before getting a token. but still, I am getting these errors.
I didn't find any pattern as such. It is happening quite randomly.

`Non-fatal Exception: com.google.android.recaptcha.RecaptchaException: Internal Error
       at com.google.android.recaptcha.internal.zzaw.zzj(:113)
       at com.google.android.recaptcha.internal.zzaw.zzd()
       at com.google.android.recaptcha.internal.zzao.invokeSuspend(:16)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:11)
       at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(ScopeCoroutine.java:6)
       at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.java:15)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:49)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.java:134)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8653)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)`

`Non-fatal Exception: com.google.android.recaptcha.RecaptchaException: Network Error
       at com.google.android.recaptcha.internal.zzbq.zza(:143)
       at com.google.android.recaptcha.internal.zzal.invokeSuspend(:150)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:11)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.java:134)
       at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.java:3)
       at kotlinx.coroutines.scheduling.TaskImpl.run(TaskImpl.java:2)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.java)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.java:14)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.java:28)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.java)`

**Device (please complete the following information):**

![image](https://github.com/GoogleCloudPlatform/recaptcha-enterprise-mobile-sdk/assets/110112051/af825cf5-7705-469c-aa9f-7282222dc032)
![image](https://github.com/GoogleCloudPlatform/recaptcha-enterprise-mobile-sdk/assets/110112051/fe83391a-1048-4655-93d6-c6f4864fe325)

**Comment by walterjgsp** [comment]
Thanks for the report @rogu01, would you mind reaching out to [recaptcha-mobile-github@google.com](mailto:recaptcha-mobile-github@google.com) with your site key so we can investigate further?

**Comment by walterjgsp** [comment]
Thanks for sending the site key @rogu01! Do you have retries implemented in your flow? 

We have an Android update scheduled for release next week (version 18.5.0-beta01) that should address the network errors you've reported. I will provide an update once the release is live

**Comment by walterjgsp** [comment]
@rogu01, could you fill this form [recaptcha-mobile-github](https://forms.gle/sThtVbNBwPh2kVfb9 please? The email that I've provided you is actually deprecated.

**Comment by walterjgsp** [comment]
@rogu01, we just released Android 18.5.0-beta01, please let us know if this version help with your issue.

**Comment by rogu01** [comment]
> Thanks for sending the site key @rogu01! Do you have retries implemented in your flow?
> 
> We have an Android update scheduled for release next week (version 18.5.0-beta01) with changes on how we do network. I will provide an update once the release is live

Yes, I have implemented retries. Whenever I am trying to get a Recaptcha token, I am checking if the Recaptcha client is initialised or not; if not, I am initialising again. Although I am already doing Recaptcha initialization in application class as well.

**Comment by rogu01** [comment]
> @rogu01, could you fill this form [recaptcha-mobile-github](https://forms.gle/sThtVbNBwPh2kVfb9) please? The email that I've provided you is actually deprecated.

Submitted

**Comment by walterjgsp** [comment]
Thanks for submitting the site key, @rogu01! Please test our new release, 18.5.0-beta01, and let us know if it improves your Network Error ratios.

**Comment by rogu01** [comment]
Hi @walterjgsp, Thanks for the reply.

To test the errors, I need to release the app, for which I can't go with the beta version of the library. Is there any plan to release a stable version of the library in the near future? If yes, then is there any approximate date for it?

**Comment by walterjgsp** [comment]
> Is there any plan to release a stable version of the library in the near future? If yes, then is there any approximate date for it?

We're pushing hard to get a stable version out the door. It's difficult to provide an exact date, I'll keep you updated on our progress.

**Comment by rogu01** [comment]
> > Is there any plan to release a stable version of the library in the near future? If yes, then is there any approximate date for it?
> 
> We're pushing hard to get a stable version out the door. It's difficult to provide an exact date, I'll keep you updated on our progress.

Could you please provide any rough estimations of the stable release of the library? like the end of this month or the first week of the next month, or something like that.

**Comment by walterjgsp** [comment]
We don't have an official release date yet, but it will likely be in the next couple months
